# nginx-proxy/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-proxy